version: '2'
services:
#################################################
  afcs:
    image: afcs
    build:
      context: .
      dockerfile: ./afcs.Dockerfile
    container_name: afcs
    working_dir: /home/user/afcs
    restart: always
    networks:
      cyberimmune:
        ipv4_address: 172.28.0.4
    ports:
      - "8080:8080"
      - "1883:1883"
      - "8883:8883"
#################################################
networks:
  cyberimmune:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
